export const ADD_MOVIES_SUCCESS = "ADD_MOVIES_SUCCESS";
export const GET_MOVIES_SUCCESS = "GET_MOVIES_SUCCESS";
export const GET_SINGLE_MOVIES_SUCCESS = "GET_SINGLE_MOVIES_SUCCESS";
export const DELETE_MOVIES_SUCCESS = "DELETE_MOVIES_SUCCESS";
export const EDIT_MOVIES_SUCCESS = "EDIT_MOVIES_SUCCESS";
